### ISSUE TITLE
Clean up previous comments

### ISSUE THREAD

**Issue by lukebakken** [basho-labs/thumbs#39]
Could there be a way to delete old comments, or preserve the past `N` comments?

https://github.com/basho/riak_s3_api/pull/19

Build history gets to be pretty large.

**Comment by davidx** [comment]
Yes definitely, 
Could implement a config value like:
```yaml
max_comments: 5 # clear out oldest build status comment to make room for newest
```
How's that look or any suggestions ?

**Comment by davidx** [comment]
@lukebakken ^^

**Comment by lukebakken** [comment]
Seems fine to me, though I would prefer #40

**Comment by davidx** [comment]
@lukebakken Yep, when that's working one could choose to disable status commenting entirely.  on the roadmap. :)
