### ISSUE TITLE
Integrate with GitHub build notification rather than via comments

### ISSUE THREAD

**Issue by lukebakken** [basho-labs/thumbs#40]
When Travis CI runs builds, it updates the "checks" section in a pull request:

![travis-ci-gh-checks](https://cloud.githubusercontent.com/assets/514926/20366610/c238721c-ac00-11e6-9cc4-1e44115d675b.png)

Rather than continuously add comments to a PR, Thumbs could hook in to this same mechanism.

**Comment by davidx** [comment]
👍 Agreed! I think that's through third party integration providers only but i'll reach out to them and see what it'd take.

**Comment by davidx** [comment]
@lukebakken I found the settings in GitHub to deploy a custom integration, will probably need to adjust behavior a bit and learn how the "checks" mechanism works. Thanks!

**Comment by lukebakken** [comment]
Awesome I'll keep an eye on this issue to follow along.
