### ISSUE TITLE
Retry doesn't blow away the build dir, should it ?

### ISSUE THREAD

**Issue by davidx** [basho-labs/thumbs#60]
When calling 'thumbot retry' it operates on the same build dir. 
Some builds don't clean up to a pristine state before each build and thus a case could be made for blowing away the build dir entirely for it to be fresh.

This build: https://github.com/basho/riak_repl/pull/764#issuecomment-265856809 had to be manually cleaned up for retry. 

Should we blow away the build dir during retries ?

**Comment by JeetKunDoug** [comment]
I would say "yes" - the most typical case that I've run across is when Github fails to let you clone some repository, but `git` creates the directory - get-deps or some other step in the build process will then continue to fail until you delete at least that directory and do get-deps again.

**Comment by davidx** [comment]
Merged and deployed: https://github.com/basho-labs/thumbs/pull/61
